"""Guardrail script for Power BI report creation.

Real .pbix files are proprietary packages generated by Power BI Desktop.
This script intentionally does not attempt to synthesize them.
"""

from pathlib import Path


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    sql_path = repo_root / "infra" / "fabric" / "sql" / "setup_reconciliation_validation.sql"

    print("[INFO] Power BI .pbix generation is not supported from this script.")
    print("[ACTION] Use Power BI Desktop and connect to view: vw_holdings_price_validation")
    print(f"[ACTION] Run SQL setup first: {sql_path}")


if __name__ == "__main__":
    main()
